export type PresetFlags = 'ALL' | 'DEFAULT';

export type SettingFlags = 'MULTIPLE' | 'HIGH_THRESHOLD' | 'DYNAMIC';

export type TechniqueFlags =
  // Windows
  | 'GPU_CAPABILITIES'
  | 'TPM'
  | 'ACPI_SIGNATURE'
  | 'POWER_CAPABILITIES'
  | 'DISK_SERIAL'
  | 'IVSHMEM'
  | 'SGDT'
  | 'SLDT'
  | 'SMSW'
  | 'DRIVERS'
  | 'REGISTRY_VALUES'
  | 'DEVICE_HANDLES'
  | 'VIRTUAL_PROCESSORS'
  | 'HYPERV_QUERY'
  | 'REGISTRY_KEYS'
  | 'AUDIO'
  | 'DISPLAY'
  | 'DLL'
  | 'VMWARE_BACKDOOR'
  | 'WINE'
  | 'VIRTUAL_REGISTRY'
  | 'MUTEX'
  | 'DEVICE_STRING'
  | 'VPC_INVALID'
  | 'VMWARE_STR'
  | 'GAMARUE'
  | 'CUCKOO_DIR'
  | 'CUCKOO_PIPE'
  | 'TRAP'
  | 'UD'
  | 'BLOCKSTEP'
  | 'DBVM'
  | 'OBJECTS'
  | 'NVRAM'
  | 'BOOT'
  | 'BOOT_LOGO'

  // Linux and Windows
  | 'SIDT'
  | 'FIRMWARE'
  | 'PCI_DEVICES'
  | 'HYPERV_HOSTNAME'
  | 'GENERAL_HOSTNAME'
  | 'VBOX_DEFAULT'

  // Linux
  | 'SMBIOS_VM_BIT'
  | 'KMSG'
  | 'CVENDOR'
  | 'QEMU_FW_CFG'
  | 'SYSTEMD'
  | 'CTYPE'
  | 'DOCKERENV'
  | 'DMIDECODE'
  | 'DMESG'
  | 'HWMON'
  | 'LINUX_USER_HOST'
  | 'VMWARE_IOMEM'
  | 'VMWARE_IOPORTS'
  | 'VMWARE_SCSI'
  | 'VMWARE_DMESG'
  | 'QEMU_VIRTUAL_DMI'
  | 'QEMU_USB'
  | 'HYPERVISOR_DIR'
  | 'UML_CPU'
  | 'VBOX_MODULE'
  | 'SYSINFO_PROC'
  | 'DMI_SCAN'
  | 'PODMAN_FILE'
  | 'WSL_PROC'
  | 'FILE_ACCESS_HISTORY'
  | 'MAC'
  | 'NSJAIL_PID'
  | 'BLUESTACKS_FOLDERS'
  | 'AMD_SEV'
  | 'TEMPERATURE'
  | 'PROCESSES'

  // Linux and MacOS
  | 'THREAD_COUNT'

  // MacOS
  | 'MAC_MEMSIZE'
  | 'MAC_IOKIT'
  | 'MAC_SIP'
  | 'IOREG_GREP'
  | 'HWMODEL'
  | 'MAC_SYS'

  // cross-platform
  | 'HYPERVISOR_BIT'
  | 'VMID'
  | 'INTEL_THREAD_MISMATCH'
  | 'AMD_THREAD_MISMATCH'
  | 'XEON_THREAD_MISMATCH'
  | 'TIMER'
  | 'CPU_BRAND'
  | 'HYPERVISOR_STR'
  | 'CPUID_SIGNATURE'
  | 'BOCHS_CPU'
  | 'KGT_SIGNATURE';
