export type PresetFlags = 'ALL' | 'DEFAULT';

export type SettingFlags =
  'MULTIPLE' | 'HIGH_THRESHOLD' | 'DYNAMIC' | 'EXPERIMENTAL';

export type TechniqueFlags =
  /* Windows */
  | 'GPU_CAPABILITIES'
  | 'ACPI_SIGNATURE'
  | 'POWER_CAPABILITIES'
  | 'DRIVERS'
  | 'HANDLES'
  | 'VIRTUAL_PROCESSORS'
  | 'AUDIO'
  | 'DISPLAY'
  | 'DLL'
  | 'WINE'
  | 'VIRTUAL_REGISTRY'
  | 'MUTEX'
  | 'VPC_INVALID'
  | 'VMWARE_STR'
  | 'GAMARUE'
  | 'CUCKOO'
  | 'TRAP'
  | 'UD'
  | 'INTERRUPT_SHADOW'
  | 'DBVM'
  | 'KERNEL_OBJECTS'
  | 'NVRAM'
  | 'CPU_HEURISTIC'
  | 'CLOCK'
  | 'MSR'
  | 'KVM_INTERCEPTION'
  | 'HYPERVISOR_HOOK'
  | 'SINGLE_STEP'
  | 'EIP_OVERFLOW'
  | 'SVM_EXCEPTIONS'
  | 'MEASURED_BOOT'
  | 'TPM'

  /* Linux and Windows */
  | 'SYSTEM_REGISTERS'
  | 'FIRMWARE'
  | 'DEVICES'
  | 'AZURE'
  | 'BOOT_LOGO'
  | 'DISK'

  /* Linux */
  | 'SMBIOS_VM_BIT'
  | 'KMSG'
  | 'CVENDOR'
  | 'QEMU_FW_CFG'
  | 'SYSTEMD'
  | 'CTYPE'
  | 'DOCKERENV'
  | 'DMIDECODE'
  | 'DMESG'
  | 'HWMON'
  | 'LINUX_USER_HOST'
  | 'QEMU_VIRTUAL_DMI'
  | 'QEMU_USB'
  | 'HYPERVISOR_DIR'
  | 'UML_CPU'
  | 'VBOX_MODULE'
  | 'SYSINFO_PROC'
  | 'DMI_SCAN'
  | 'PODMAN_FILE'
  | 'WSL_PROC'
  | 'FILE_ACCESS_HISTORY'
  | 'MAC'
  | 'CONTAINER_PID'
  | 'BLUESTACKS_FOLDERS'
  | 'AMD_SEV_MSR'
  | 'TEMPERATURE'
  | 'CGROUP'
  | 'PROCESSES'

  /* Linux and MacOS */
  | 'THREAD_COUNT'

  /* MacOS */
  | 'MAC_MEMSIZE'
  | 'MAC_IOKIT'
  | 'MAC_SIP'
  | 'IOREG_GREP'
  | 'HWMODEL'
  | 'MAC_SYS'

  /* Cross-platform */
  | 'HYPERVISOR_BIT'
  | 'VMID'
  | 'THREAD_MISMATCH'
  | 'TIMER'
  | 'CPU_BRAND'
  | 'HYPERVISOR_STR'
  | 'CPUID_SIGNATURE'
  | 'BOCHS_CPU'
  | 'KGT_SIGNATURE';
