name: Build test

on:
  workflow_dispatch:

jobs:
  macos-x64-test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm i
      - name: Build test
        run: npm run build:test

  macos-arm64-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm i
      - name: Build test
        run: npm run build:test

  windows-x64-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm i
      - name: Build test
        run: npm run build:test

  # windows-arm64-test:
  #   runs-on: windows-11-arm
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: 'recursive'
  #     - uses: fregante/setup-git-user@v2
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 22
  #     - name: Install dependencies
  #       run: npm i
  #     - name: Build test
  #       run: npm run build:test

  linux-x64-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Select Clang
        run: |
          echo "CC=clang"   >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
          echo "CXXFLAGS=-std=c++20 -fexceptions" >> $GITHUB_ENV
      - name: Install dependencies
        run: npm i
      - name: Build test
        run: npm run build:test

  linux-arm64-test:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Select Clang
        run: |
          echo "CC=clang"   >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
          echo "CXXFLAGS=-std=c++20 -fexceptions" >> $GITHUB_ENV
      - name: Install dependencies
        run: npm i
      - name: Build test
        run: npm run build:test
